shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*

overrides:
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  chokidar: 4.0.1
  semver: 7.7.3
  undici-types: 7.19.2

catalog:
  '@antfu/eslint-config': ^7.2.0
  '@codemod.com/cli-win32-x64-msvc': ^1.3.3
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slot': ^1.2.4
  '@tailwindcss/postcss': ^4.1.18
  '@types/node': ^25.1.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': ^8.54.0
  '@typescript-eslint/parser': ^8.54.0
  bumpp: ^10.3.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  codemod: ^1.3.14
  commitizen: ^4.3.1
  cz-git: ^1.12.0
  eslint: ^9.39.2
  eslint-config-next: 16.0.1
  globals: ^17.2.0
  lint-staged: ^16.2.7
  lucide-react: ^0.563.0
  next: 16.0.1
  next-auth: ^4.24.13
  publint: ^0.3.1
  react: 19.2.0
  react-dom: 19.2.0
  rimraf: ^6.1.2
  shadcn: ^3.8.0
  simple-git-hooks: ^2.13.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsdown: ^0.17.3
  turbo: ^2.8.0
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  vitepress: ^1.6.4
  vitest: ^4.0.15
  vitest-package-exports: ^0.1.1

ignoredBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - simple-git-hooks
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
